version: '3'

services:
  db: 
    image: postgres:14.0-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8007"
    volumes:
      - project:/usr/src/app
    ports:
      - "8007:8007"
    depends_on:
      - db

  redis:
    image: redis
    restart: always
    expose:
      - "6379:6379"
  celery:
    build: .
    command: >
      bash -c "celery -A cinemaAva worker"
    volumes:
      - project:/usr/src/app/
    depends_on:
      - db
      - web
      - redis
  celery_beat:
    build: .
    command: >
      bash -c "celery -A cinemaAva beat"
    volumes:
      - project:/usr/src/app/
    depends_on:
      - db
      - web
      - celery
      - redis
 
volumes:
  postgres_data:
  project:


   
  # flower:
  #   build: .
  #   command: >
  #     bash -c "celery -A cinemaAva flower --adress=127.0.0.1 --port=5566&"
  #   volumes:
  #     - project:/usr/src/app
  #   ports:
  #     - "8006:8006"
  #   depends_on:
  #     - db
  #     - redis